### ISSUE TITLE
Change system.make approach in Makefile

### ISSUE THREAD

**Issue by davidbowler** [OrderN/CONQUEST-release#332]
At the moment, the Makefile uses the command `hostname -d` to identify a system and uses a `system.make` file based on that name.  However, the command has been found to behave differently on different platforms, and some HPC centres are concerned about giving out hostnames.

The suggestion is that we default to `system.make` by setting the variable `SYSTEM` to be blank; the user can give the command `make SYSTEM=name` to use the `system.name.make` file if they wish, or simply or edit copy an appropriate `system.make` template file.  In this case we should not have a `system.make` file in the repository (so that users need to select an appropriate file).

We should include some form of documentation for the templates: either in a README.md file or in a header (or even both!).

**Comment by tkoskela** [comment]
Currently the Makefile defaults to `system.make` if the variable `SYSTEM` is blank. This happens e.g. on my laptop because `hostname -d` returns nothing, but obviously if `hostname -d` returns a value but you want to ignore it you'd have to set `SYSTEM=` on the command line. We could change this to be the default behaviour and have the user set `SYSTEM` on the command line in order to use one of the files in the `system` directory, if that's preferable. The file `system.make` is in the root `.gitignore` so it is not being version controlled. The `system.example.make` is intended to be a template you can start from.

A couple of slightly tangential points I want to mention
1. We should think about what should be in the `system.make` files and what shouldn't, see #329 
2. Rather than having the system-specific config set by the user, we should really be using autotools or cmake to detect them automatically. That would resolve many problems.

**Comment by davidbowler** [comment]
After discussing this with the other core team members, we have decided that we will tweak this approach slightly so that `system.make` is the default name, but can be changed using `make SYSTEM=name`.  I'll open a branch and do this in the next day or two so that we can release v1.3, and other tweaks to the Makefile can follow.

**Comment by davidbowler** [comment]
Closed by #335
